### PR TITLE
README

### PR DESCRIPTION
**Pull request by mtrudel**

### CODE REVIEW

**Comment by mtrudel** [comment]
COMMENT

**Comment by iamdavidjackson** [comment]
Looks great!

**Comment by mtrudel** [comment]
asdf

**Comment by mtrudel** [comment]
@benchmark

**Comment by mtrudel** [comment]
asdf

**Comment by mtrudel** [comment]
@benchmark

**Comment by mtrudel** [comment]
asdf

**Comment by mtrudel** [comment]
@benchmark

**Comment by iamdavidjackson** [comment]
@benchmark

**Pull request merged**
